version: '3.8'

services: 
  app:
    image: '73c8888810708911aab8259fc7b29b3e83afa5de562e3ce07ad5f9b9badcfbe9'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on: 
      - db

  db:
    image: 'postgres:16'
    container_name: db
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'