create database postgres;

create table V_FIRM (
                        FIRMID int primary key generated by default as identity,
                        TLGR varchar NOT NULL,
                        DISLOC varchar NOT NULL
);

create table VIDTC (
                       VIDT int primary key generated by default as identity,
                       SHNAME varchar NOT NULL,
                       FULLNAME varchar
);

create table VFIRM_VIDTC(
                            FIRMID int REFERENCES V_FIRM(FIRMID),
                            VIDT int REFERENCES VIDTC(VIDT),
                            PRIMARY KEY (FIRMID, VIDT)
);

create table TIPTR (
                       TID int primary key generated by default as identity,
                       TNAME varchar NOT NULL,
                       VIDT int NOT NULL REFERENCES VIDTC(VIDT),
                       PRIZNGR varchar
);

create table PTS (
                     UIN int primary key generated by default as identity,
                     UNTS int NOT NULL,
                     TID int NOT NULL REFERENCES TIPTR(TID),
                     FIRMID int NOT NULL REFERENCES V_FIRM(FIRMID),
                     GRP int NOT NULL,
                     NORMT int NOT NULL,
                     DATASP timestamp
);


insert into V_FIRM(TLGR, DISLOC) VALUES ('RZD', 'Russia');
insert into VIDTC(shname, fullname) VALUES ('Wagon', 'Freight wagon');
insert into TIPTR(TNAME, VIDT, PRIZNGR) VALUES ('Freight', 1, 'Smbdy');
insert into PTS(UNTS, TID, FIRMID, GRP, NORMT) VALUES (198, 1, 1, 100, 20);
insert into VFIRM_VIDTC(firmid, vidt) VALUES (1, 1);